version: "3.3"
services:
    db:
        build: mysql
        ports:
            - "3306:3306"
        volumes:            
            - ./tests:/home/tests
            - ./tests_output:/home/tests_output
            - ./reports:/home/reports