version: "3.3"
services:
    web:
        build: apache
        ports:
            - "80:80"          
        volumes:
            - ./www:/var/www/html
            - ./tests:/var/www/html/tests
    db:
        build: mysql
        ports:
            - "3306:3306"    